name: CowSay
on:
  push:
    branches:
      - main

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/cowsay-action@v1.x
        with:
          text: "This is pretty cool right? RIGHT??"
